name: chess-ratings

services:
  nginx:
    container_name: nginx
    build: ./nginx
    volumes:
      - ./nginx/config.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:8080"
    depends_on:
      - api

  api:
    container_name: api
    build:
      context: ./python
      dockerfile: api.Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - database
      - loader

  loader:
    container_name: loader
    build:
      context: ./python/
      dockerfile: loader.Dockerfile
    volumes:
      - ./python/loader:/var/loader
    depends_on:
      - database

  database:
    container_name: database
    build: ./database
    volumes:
      - ./database/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=database
    ports:
      - "5432"